### PR TITLE
710 - Question playback

### PR DESCRIPTION
**Pull request by tgandrews**
### What is the context of this PR?
Implement the CRUD schema for question confirmation pages.

### How to review 
Ensure the schema is valid

### CODE REVIEW

**Comment by tgandrews** [comment]
[Playback confirmation](https://trello.com/c/WniDYUci/709-playback-confirmation)

**Review by samiwel — APPROVED** [review]
LGTM

**Review by adammahmood — APPROVED** [review]
LGTM

**Review by adammahmood — CHANGES_REQUESTED** [review]
LGTM - However, let's check if `alias` field is required or not before merging.

**Review by adammahmood — APPROVED** [review]

**Pull request merged**
